[project]
name = "flowtracks-examples"
version = "0.1.0"
description = "Gallery of flowtracks notebooks in Jupyter and marimo"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flowtracks",
    "h5py>=3.15.1",
    "hdf5storage>=0.2.2",
    "marimo>=0.23.9",
    "matplotlib>=3.10.8",
    "pandas>=3.0.1",
    "plotly>=6.5.2",
    "pyzmq>=27.1.0",
    "ruff>=0.15.4",
    "tables>=3.11.0",
    "xarray>=2024.1.0",
    "zarr>=3.0.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.uv.sources]
flowtracks = { path = "../postptv", editable = true }

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
